baseURL = 'https://ack.gg/'
languageCode = 'en-us'
title = 'Acknowledged: Good Game'
theme = "hulga"
paginate = 15


[params]
  keywords = "servers, cloud, sysadmin, devops"
  description = "Lesson acknowledged: Good Game."
  subtitle = "Servers going beep bup"
  math = false
  postcss = false
  showSummary = true
  termPaginate = 10
  toc = true
  autoCollapseToc = true
  darkMedia = true
  heroBold = false
  heroSteamDeck = false
  pwa = true
  noCDN = true

# to enable different hightlight themes in light/dark mode 
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  
[menu]
  [[menu.main]]
    identifier = "index"
    name = "Home"
    url = "/"
    weight = 1
#  [[menu.main]]
#    identifier = "archives"
#    name = "Archives"
#    url = "/archives/"
#    weight = 2
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 3
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 5

[taxonomies]
category = "categories"
tag = "tags"